account_address: "REPLACE_WITH_GENERATED_ACCOUNT_ADDRESS"
account_private_key: "REPLACE_WITH_GENERATED_ACCOUNT_PRIVATE_KEY"
consensus_private_key: "REPLACE_WITH_GENERATED_CONSENSUS_PRIVATE_KEY"
network_private_key: "REPLACE_WITH_GENERATED_NETWORK_PRIVATE_KEY"
